### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by filiperochalopes** [fundamentos-dev/biblia#1]
Aqui vão as funcionalidades previstas do projeto:

- [ ] Fase 1: Apenas campo de busca com referências
- [ ] Fase 2: Criação de anotações: cada tag de anotação pode ter uma cor e um título, podemos ver a lista de todas elas
- [ ] Fase 3: Leitura corrida das escrituras ao selecionar um Livro, capítulo e versículo
- [ ] Fase 4: Busca avançada utilizando NLP e IA para buscar por sinônimos e contexto

**Comment by filiperochalopes** [comment]
Adicionado ao README.md
